#include <bits/stdc++.h>
using namespace std;

const long long MOD = 1000000007;

long long ans;

void solve(long long N, std::vector<long long> A){
    for(int i=0;i<N-1;i++){
        for(int j=i+1;j<N;j++){
         
            // cout << "ans=" << ans << endl; 
            // cout << A[j] << endl;
            ans += (A[i] ^ A[j]);
          
           
        }
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve(N, std::move(A));
    ans = ans % MOD;
    cout << ans << endl;
    return 0;
}
