#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long X, long long D){

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long X;
    scanf("%lld",&X);
    long long D;
    scanf("%lld",&D);
    solve(N, X, D);
    return 0;
}
