#include <bits/stdc++.h>
using namespace std;


void solve(std::string S){
    int ans =0;
    string days[7] = {"SUN","MON","TUE","WED","THU","FRI","SAT"};
    for(auto day:days){
        if(S==day){
            cout <<7-ans << endl;
            break;
        }
        ans++;
    }
}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
