#include <bits/stdc++.h>
using namespace std;




void solve(long long A, long long B, long long X){
    int degree =-1;
    for(int i =9;i>=0;i--){
        long long num = A * pow(10,i) + B*(i+1);
        if(num<X){
            degree = i;
            break;
        }
    }
    // cout << degree << endl;
    if(degree == 9){
        long long ans = pow(10,degree);
        cout << ans << endl;
        return;
    }
    if(degree == -1){
        cout << 0 << endl;
        return;
    }

    long long y = X- B*(degree+1);
    long long ans = y/A;
    if(ans >= (long long) pow(10,degree+1)){
        ans =  pow(10,degree+1) -1;
    }
    cout << ans << endl;


}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    long long X;
    scanf("%lld",&X);
    solve(A, B, X);



    return 0;
}
