#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::string S){
    string alphabets = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    for(int i=0;i<S.size();i++){
        for(int j=0;j<alphabets.size();j++){
            if(S[i] == alphabets[j]){
                S[i] = alphabets[(j+N)%alphabets.size()];
                break;
            }
        }
    }
    cout << S << endl;


}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::string S;
    std::cin >> S;
    solve(N, S);
    return 0;
}
