#include <bits/stdc++.h>
using namespace std;


void solve(std::string S){
    int len = S.size();
    int ans =0;
    for(int i= 0;i<len;i++){
        if(S[i] != S[len-1-i]){
            // cout << S[i] << S[len-1-i] << endl;
            ans++;
        }
    }
    ans /= 2;
    cout << ans << endl;

}

// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::string S;
    std::cin >> S;
    solve(S);
    return 0;
}
